##############CONFIG###############
language: php

dist: trusty

php:
    - 7.1.1

services:
    - mysql



###############BUILD###############
before_install:
    - composer update

install:

before_script:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS newbDB;'

script:
    - phpunit

after_script:
    - mysql -e 'DROP DATABASE IF EXISTS newbDB;'



############NOTIFICATION###########
notifications:
  slack:
      rooms:
          - jobobagr:YmqvkAPUlhqRKEYXCgJ1qVQa#devops #could be encrypted but oh well
      on_success: always  #default: change
      on_failure: always  #default: always