language: php

dist: trusty

php:
    - 7.1.1

services:
    - mysql



###############BUILD###############

before_install:
    - composer update
    - mysql -e 'CREATE DATABASE IF NOT EXISTS newbDB;'

install:
   # - php bin/console doctrine:database:create --if-not-exists
    #- php bin/console doctrine:schema:update --force

before_script:
    #- php bin/console server:run

script:
    - phpunit

after_script:
    # delete db for tests (newbDB -> doctrine)



############NOTIFICATION#########

notifications:
  slack:
      rooms:
          - jobobagr:YmqvkAPUlhqRKEYXCgJ1qVQa#devops #could be encrypted but welp
      on_success: always  #default: change
      on_failure: always  #default: always