language: php

dist: trusty

php:
    - 7.1.1

before_install:
    - composer update
    - mysql -e 'CREATE DATABASE IF NOT EXISTS newbDB;'

services:
    - mysql

install:
    - php bin/console doctrine:database:create
    - php bin/console doctrine:schema:update --force

before_script:
    #- php bin/console server:run

script:
    - phpunit