# docker-compose.yml
version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
             MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
             MYSQL_DATABASE: ${MYSQL_DATABASE}
             MYSQL_USER: ${MYSQL_USER}

    php:
        build: php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - /Users/Quentin/Developpement/PHP/newb/newb:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 8080:80
        links:
            - php
        volumes_from:
            - php
        depends_on:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx